accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('sign_in', views.sign_in, name='sign_in'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('sign_out', views.sign_out, name='sign_out'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/change_password', views.change_password, name='change_password'),
]

project_7/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', views.home, name='home'),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from cropperjs.models import CropperImageField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(default='')
    confirm_email = models.EmailField(default='')
    city = models.CharField(max_length=255, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    bio = models.CharField(max_length=500, blank=True)
    hobby = models.CharField(max_length=255, blank=True)
    avatar = CropperImageField(default='sample.png', upload_to='avatars/')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

@property
def password_validator_target(self):
    return ' '.join([
        self.first_name + self.last_name, 
        self.last_name + self.first_name,
        self.first_name + self.username,
        self.username + self.first_name,
        self.username + self.last_name,
        self.last_name + self.username,
        ])

accounts/forms.py
import re
from PIL import Image

from django.core import validators
from django.core.exceptions import ValidationError
from django.core.files import File
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import PasswordChangeForm
from django import forms

from flatpickr import DatePickerInput
from zxcvbn_password.fields import PasswordField, PasswordConfirmationField
from tinymce.widgets import TinyMCE
from . import models


class AvatarForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = [
            "avatar",
        ]

    class Media:
        css = {"all": ("/assets/css/global.css",)}


class UserForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = [
            "first_name",
            "last_name",
        ]


class ProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=DatePickerInput())
    bio = forms.CharField(
        widget=TinyMCE(attrs={"cols": 70, "rows": 20}),
        validators=[validators.MinLengthValidator(10)],
    )

    class Meta:
        model = models.Profile
        fields = [
            "email",
            "confirm_email",
            "city",
            "date_of_birth",
            "hobby",
            "bio",
        ]

    class Media:
        css = {"all": ("/assets/css/global.css",)}

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        confirm_email = cleaned_data.get("confirm_email")

        if email and confirm_email:
            if email != confirm_email:
                raise forms.ValidationError("Emails must match. Please check again")


class ChangePasswordForm(PasswordChangeForm):
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(ChangePasswordForm, self).__init__(user, *args, **kwargs)

    old_password = forms.CharField(widget=forms.PasswordInput)
    new_password1 = PasswordField()
    new_password2 = PasswordConfirmationField(confirm_with=new_password1)

    class Meta:
        form = PasswordChangeForm
        fields = [
            "old_password",
            "new_password1",
            "new_password2",
        ]

    class Media:
        css = {"all": ("/assets/css/global.css",)}

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render

from . import forms
from . import models


def sign_in(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse("accounts:view_profile",))
                else:
                    messages.error(request, "That user account has been disabled.")
            else:
                messages.error(request, "Username or password is incorrect.")
    return render(request, "accounts/sign_in.html", {"form": form})


def sign_up(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password1"],
            )
            login(request, user)
            messages.success(request, "You're now a user! You've been signed in, too.")
            return HttpResponseRedirect(reverse("accounts:view_profile",))
    return render(request, "accounts/sign_up.html", {"form": form})


def sign_out(request):
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse("accounts:sign_in"))


@login_required
def view_profile(request):
    return render(request, "accounts/view_profile.html")


@login_required
def edit_profile(request):
    user_form = forms.UserForm(instance=request.user)
    profile_form = forms.ProfileForm(instance=request.user.profile)
    avatar_from = forms.AvatarForm(instance=request.user.profile)

    if request.method == "POST":
        user_form = forms.UserForm(request.POST, instance=request.user)
        profile_form = forms.ProfileForm(request.POST, instance=request.user.profile)
        avatar_from = forms.AvatarForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if user_form.is_valid() and profile_form.is_valid() and avatar_from.is_valid():
            user_form.save()
            profile_form.save()
            avatar_from.save()
            messages.success(request, "Profile updated !")
            return HttpResponseRedirect(reverse("accounts:view_profile",))

    return render(
        request,
        "accounts/edit_profile.html",
        {
            "user_form": user_form,
            "profile_form": profile_form,
            "avatar_form": avatar_from,
        },
    )


@login_required
def change_password(request):
    form = forms.ChangePasswordForm(request.user)

    if request.method == "POST":
        form = forms.ChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Your password was successfully updated!")
            return HttpResponseRedirect(reverse("accounts:change_password",))

    return render(request, "accounts/change_password.html", {"form": form})

project_7/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Change Password{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row no-gutter">
	<div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
	<div class="col-md-8 col-lg-6">
	  <div class="login d-flex align-items-center py-5">
		<div class="container">
		  <div class="row">
			  {% if messages %}
			<ul>
			  {% for message in messages %}
				  <li>{{ message }}</li>
			  {% endfor %}
			</ul>
			{% endif %}
			<div class="col-md-9 col-lg-8 mx-auto">
			  <h3 class="login-heading mb-4">Change Password !</h3>
			  <form method="post" action="">
				  {% csrf_token %}
				  <div class="form-label-group">
				  {{ form.old_password }}
				  <label for="id_old_password">Old password</label>
				  </div>
				  <div class="form-label-group">
				  {{ form.new_password1 }}
				  <label for="id_new_password1">New password</label>
				  </div>
				  <div class="form-label-group">
				  {{ form.new_password2 }}
				  <label for="id_new_password2">Confirm password</label>
				  </div>

				<input class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit" value="SAVE">
			  </form>
			  {{ form.errors }}
			</div>
		  </div>
		</div>
	  </div>
	</div>
  </div>
</div>
{% endblock %}
{% block js %}
{{ form.media }}
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row no-gutter">
	<div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
	<div class="col-md-8 col-lg-6">
	  <div class="login d-flex align-items-center py-5">
		<div class="container">
		  <div class="row">
			  {% if messages %}
			<ul>
			  {% for message in messages %}
				  <li>{{ message }}</li>
			  {% endfor %}
			</ul>
			{% endif %}
			<div class="col-md-9 col-lg-8 mx-auto">
			  <h3 class="login-heading mb-4">Edit Your Profile !</h3>
			  <form method="post" action="" enctype="multipart/form-data">
				  {% csrf_token %}
                  {{ avatar_form }}
				  {{ user_form.as_p }}
				  {{ profile_form.as_p}}

				<input class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit" value="SAVE">
			  </form>
			  {{ form.errors }}
			</div>
		  </div>
		</div>
	  </div>
	</div>
  </div>
</div>
{% endblock %}
{% block js %}
{{ avatar_form.media }}
{{ user_form.media }}
{{ profile_form.media }}
<script>
	var form_fields = document.getElementsByTagName('input');
	form_fields[2].placeholder='First name';
	form_fields[3].placeholder='Last name';
	form_fields[4].placeholder='Email';
	form_fields[5].placeholder='Confirm email';
	form_fields[6].placeholder='City';
	form_fields[8].placeholder='Hobby';

	for (var field in form_fields){
		form_fields[field].className += 'form-control'
	}
</script>
{% endblock %}

accounts/templates/accounts/sign_in.html
{% extends "base.html" %}
{% load static %}
{% block title %}Sign In{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row no-gutter">
	<div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
	<div class="col-md-8 col-lg-6">
	  <div class="login d-flex align-items-center py-5">
		<div class="container">
		  <div class="row">
			  {% if messages %}
			<ul>
			  {% for message in messages %}
				  <li>{{ message }}</li>
			  {% endfor %}
			</ul>
			{% endif %}
			<div class="col-md-9 col-lg-8 mx-auto">
			  <h3 class="login-heading mb-4">Welcome back!</h3>
			  <form method="post" action="{% url 'accounts:sign_in' %}">
				  {% csrf_token %}
				<div class="form-label-group">
				  {{ form.username }}
				  <label for="id_username">Username</label>
				</div>

				<div class="form-label-group">
				  {{ form.password }}
				  <label for="id_password">Password</label>
				</div>

				<button class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Sign in</button>
				<div class="text-center">
				  <p>Don't have an Account ?<a class="small" href="{% url 'accounts:sign_up' %}"> Sign Up !</a></p></div>
			  </form>
			  {{ form.errors }}
			</div>
		  </div>
		</div>
	  </div>
	</div>
  </div>
</div>
{% endblock %}
{% block js %}
<script>
	var form_fields = document.getElementsByTagName('input');
	form_fields[1].placeholder='Username..';
	form_fields[2].placeholder='Password..';

	for (var field in form_fields){
		form_fields[field].className += 'form-control'
	}
</script>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends "base.html" %}
{% load static %}
{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row no-gutter">
	<div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
	<div class="col-md-8 col-lg-6">
	  <div class="login d-flex align-items-center py-5">
		<div class="container">
		  <div class="row">
			  {% if messages %}
			<ul>
			  {% for message in messages %}
				  <li>{{ message }}</li>
			  {% endfor %}
			</ul>
			{% endif %}
			<div class="col-md-9 col-lg-8 mx-auto">
			  <h3 class="login-heading mb-4">Register !</h3>
			  <form method="post" action="{% url 'accounts:sign_up' %}">
				  {% csrf_token %}
				<div class="form-label-group">
				  {{ form.username }}
				  <label for="id_username">Username</label>
				</div>

				<div class="form-label-group">
				  {{ form.password1 }}
				  <label for="id_password1">Password</label>
				</div>

				<div class="form-label-group">
				  {{ form.password2 }}
				  <label for="id_password2">Confirm Password</label>
				</div>

				<input class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit" value="Sign Up">
				<div class="text-center">
				  <p>Already have an Account ?<a class="small" href="{% url 'accounts:sign_in' %}"> Sign In !</a></p></div>
			  </form>
			  {{ form.errors }}
			</div>
		  </div>
		</div>
	  </div>
	</div>
  </div>
</div>
{% endblock %}
{% block js %}
<script>
	var form_fields = document.getElementsByTagName('input');
	form_fields[1].placeholder='Username';
	form_fields[2].placeholder='Password';
	form_fields[3].placeholder='Confirm Passowrd';

	for (var field in form_fields){
		form_fields[field].className += 'form-control'
	}
</script>
{% endblock %}

accounts/templates/accounts/view_profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}User Profile{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row no-gutter">
	<div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
	<div class="col-md-8 col-lg-6">
	  <div class="login d-flex align-items-center py-5">
		<div class="container">
		  <div class="row">
			<div class="col-md-9 col-lg-8 mx-auto">
			  <h3 class="login-heading mb-4">Welcome {{ user.username|title }}!</h3>
				<div class="form-label-group">
					<img class="align-self-center img-fluid rounded rounded-circle mr-2 my-0" style="width: 256px; height: 256px;"
					src="{{ user.profile.avatar.url }}"/>
              		<button class="btn btn-primary" onclick="window.location.href='{% url 'accounts:edit_profile' %}';">
						Edit Profile
						</button>
						<h4 class="login-heading mb-4">First name: {{ user.first_name }}</h4>
						<h4 class="login-heading mb-4">Last name: {{ user.last_name }}</h4>
						<h4 class="login-heading mb-4">Email: {{ user.profile.email }}</h4>
						<h4 class="login-heading mb-4">Date of birth: {{ user.profile.date_of_birth }}</h4>
						<h4 class="login-heading mb-4">City: {{ user.profile.city }}</h4>
						<h4 class="login-heading mb-4">Hobby: {{ user.profile.hobby }}</h4>
						<h4 class="login-heading mb-4">Bio: {{ user.profile.bio|safe }}</h4>
				</div>

			</div>
		  </div>
		</div>
	  </div>
	</div>
  </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %} | Django Profile Project</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/global.css' %}" rel="stylesheet">
  {% block css %}{% endblock %}
  {% block head %}{% endblock %}

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="/">Start</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:sign_up' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:sign_in' %}">Sign In</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:view_profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_password' %}">Change Password</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:sign_out' %}">Sign Out</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  {% block content %}
  {% endblock %}


  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'jquery/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  {% block js %}{% endblock %}

</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
  <div class="row no-gutter">
	<div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
	<div class="col-md-8 col-lg-6">
	  <div class="login d-flex align-items-center py-5">
		<div class="container">
		  <div class="row">
			<div class="col-md-9 col-lg-8 mx-auto">
			  <h3>Welcome to Django Profile Project !</h3>
			</div>
		  </div>
		</div>
	  </div>
	</div>
  </div>
</div>
{% endblock %}